title:            tail-island
description:      プログラミングとバイクが面白くてたまらない。
name:             OJIMA Ryoji
email:            rojima1@gmail.com
url:              https://tail-island.github.io
github:           tail-island
twitter_username: tail-island
gems:             [jekyll-paginate]
markdown:         redcarpet
paginate:         3
